[tool.ruff]
# E741: ambiguous variable name
lint.ignore=["E741"]
line-length=100

[tool.pytest.ini_options]
addopts="--strict-markers"
markers=["skip_ci", "img_dir_gen", "skip_pmbv2"]
timeout=20

# Kill all threads on timeout
timeout_method="thread"

log_cli=1
log_cli_level="CRITICAL"
log_cli_format="%(message)s"
log_file="pytest.log"
log_file_level="DEBUG"
log_file_format="%(asctime)s [%(levelname)8s] %(threadName)15s %(message)s (%(filename)s:%(lineno)s)"
log_file_date_format="%Y-%m-%d %H:%M:%S"
