apiVersion: v1
kind: ConfigMap
metadata:
  name: pmos-caddy-config
data:
  Caddyfile: |
    {
      admin off
    }

    :8080 {
      @health path /healthz
      respond @health "ok" 200

      reverse_proxy https://samcday-pmos.fsn1.your-objectstorage.com {
        header_up Host samcday-pmos.fsn1.your-objectstorage.com
      }
    }
